start_date: 2023-01-01T00:00:00  
end_date: 2023-01-01T00:00:00

checkpoints:
  forecaster:
    checkpoint_path: /leonardo_work/EUHPC_R04_079/hhaugen/experiments/ens_wind_speed/checkpoint/399f98e6955e4f8392ae2b1f5c1c6e1d/inference-last.ckpt
    leadtimes: 9

frequency: 6h

global_land_dataset: ${datasets}/aifs-ea-an-oper-0001-mars-n320-1979-2023-6h-v1-land.zarr
global_atm_dataset: ${datasets}/aifs-ea-an-oper-0001-mars-n320-1979-2023-6h-v8.zarr
dataset_meps: ${datasets}/aifs-meps-2.5km-2020-2025-6h-v7.zarr

workdir: ??
datasets: /leonardo_work/AIFAC_5C0_154/weathergen/data/
output: ??
verif_src_path: /leonardo_work/EUHPC_R04_079/bris/verification/nordic/6h/202206_202305/
verif_dst_path: ??
ps_dst_folder: ??

ps_fname: ??
verif_src_fname: MEPS_2.5km.nc
verif_dst_fname: ??

dataset:
  cutout:
    - dataset: ${dataset_meps}
      trim_edge: 50
      reorder: sort
    - join:
      - dataset: ${global_atm_dataset}
        drop: ["sdor", "slor", "cp", "u_600", "v_600", "z_600", "t_600", "q_600", "w_600"]
      - dataset: ${global_land_dataset}
        select: ["lcc", "mcc", "hcc", "tcc", "strd", "ssrd"]
      adjust: ["start", "end"]
      reorder: sort
  min_distance_km: 0
  adjust: all

dataset_verif: 
  dataset:
    dataset: ${dataset_meps}
    trim_edge: 100

# If the user wants to release GPU cache and memory
# This option releases unused cached/memory used by torch
release_cache: False

# Determine how much the encoder and decoder is chunked
inference_num_chunks: 1

dataloader:
  datamodule:
    _target_: bris.data.dataset.NativeGridDataset
    _convert_: all

hardware:
  num_gpus_per_node: ${oc.decode:${oc.env:SLURM_GPUS_PER_NODE}}
  num_nodes: ${oc.decode:${oc.env:SLURM_NNODES}}
  num_gpus_per_model: 4
  num_members: 2

model:
  _target_: bris.model.brispredictor.BrisPredictor
  _convert_: all

routing:
  - decoder_index: 0
    domain_index: 0
    outputs:
      - netcdf:
          filename_pattern: ${output}predictions/test_pred_%Y%m%dT%HZ.nc
          variables: ['2t', 'msl', 'tp', '2d', 'tcc', 'z_500']
          extra_variables: [ws]
          domain_name: meps
#      - verif:
#          filename: ${verif_dst_path}/t2m/${verif_dst_fname}
#          variable: 2t
#          units: degC
#          elev_gradient: -0.0065
#          obs_sources: 
#            - anemoidataset:
#                dataset: ${dataset_verif}            
#                variable: 2t

#      - powerspectrum_gridded:
#          filename: ${ps_dst_folder}/z_500/${ps_fname}
#          variable: z_500
#          domain_name: meps
#      - powerspectrum_gridded:
#          filename: ${ps_dst_folder}/t_850/${ps_fname}
#          variable: t_850
#          domain_name: meps
#      - powerspectrum_gridded:
#          filename: ${ps_dst_folder}/ws/${ps_fname}
#          variable: ws
#          domain_name: meps

#      - verif:
#          filename: ${verif_dst_path}/t2m/${verif_dst_fname}
#          variable: 2t
#          units: degC
#          elev_gradient: -0.0065
#          obs_sources:
#             - verif:
#                 filename: ${verif_src_path}/t2m/${verif_src_fname}
#      - verif:
#          filename: ${verif_dst_path}/ws10m/${verif_dst_fname}
#          variable: ws
#          units: m/s
#          obs_sources:
#             - verif:
#                 filename: ${verif_src_path}/ws10m/${verif_src_fname}
#      - verif:
#          filename: ${verif_dst_path}/mslp/${verif_dst_fname}
#          variable: msl
#          units: hPa
#          obs_sources:
#             - verif:
#                 filename: ${verif_src_path}/mslp/${verif_src_fname}
#      - verif:
#          filename: ${verif_dst_path}/precip6h/${verif_dst_fname}
#          variable: tp
#          units: mm
#          obs_sources:
#            - verif:
#                filename: ${verif_src_path}/precip6h/${verif_src_fname}
